'use client';
import {useEffect,useState} from 'react';
export default function SignIn(){
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[codeMode,setCodeMode]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const error=new URLSearchParams(window.location.search).get('error');if(error)setError(error==='workspace'?'You are signed in, but your workspace could not load. Return to the app to retry.':'That sign-in link is invalid or expired, or was opened in another browser. Request a new link here.');},[]);
 async function submit(action:'send'|'verify'){
  setBusy(true);setError('');setMessage('');
  try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email,code,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});const d=await r.json();if(!r.ok)throw Error(d.error);if(action==='verify'){window.location.assign('/');return;}setSent(true);setMessage('Sign-in email sent. Check your inbox and spam folder.');}catch(e){setError(e instanceof Error?e.message:'Sign-in is temporarily unavailable.');}finally{setBusy(false);}
 }
 return <main className="auth-page"><section className="auth-card"><a className="brand" href="/"><span className="brandmark">↗</span>growth<span>mentor</span></a><p className="eyebrow">YOUR PROGRESS, WHEREVER YOU GO</p><h1>{sent?'Check your email.':'Welcome to your next chapter.'}</h1><p className="muted">{sent?`Follow the sign-in link sent to ${email}. Open it in this browser to keep your demo goals.`:'Sign in or create an account with your email. No password to remember.'}</p>{error&&<div className="alert" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}{(!sent||codeMode)&&<form onSubmit={e=>{e.preventDefault();submit(codeMode?'verify':'send');}}>{!codeMode?<label className="field"><span>Email address</span><input name="email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254} placeholder="you@example.com" autoFocus/></label>:<label className="field"><span>Sign-in code</span><input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,10}" value={code} onChange={e=>setCode(e.target.value.trim())} required minLength={6} maxLength={10} placeholder="Enter your code" autoFocus/></label>}<button className="primary" disabled={busy}>{busy?'Please wait…':codeMode?'Verify and sign in':'Email me a sign-in link'}</button></form>}{!codeMode&&<button className="text-button auth-existing" disabled={busy} onClick={()=>{if(!/^\S+@\S+\.\S+$/.test(email)){setError('Enter your email address first.');return;}setCodeMode(true);setError('');}}>I have an email code instead</button>}{(sent||codeMode)&&<div className="auth-links"><button className="text-button" disabled={busy} onClick={()=>submit('send')}>Send a new link</button><button className="text-button" disabled={busy} onClick={()=>{setSent(false);setCodeMode(false);setCode('');setError('');setMessage('');}}>Use a different email</button></div>}<p className="footnote">On your first sign-in, this browser’s demo goals become part of your account. Returning users open their existing account workspace.</p><a className="text-button" href="/">← Continue with the demo</a></section></main>;
}
